baseURL = "http://ak3n.com/"
languageCode = "en-us"
title = "ak3n.com"
theme = "theme"

[params]
    sitename = "ak3n.com"

[markup]
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    tabWidth = 4